server:
  port: 8080

spring:
  datasource:
    url: "jdbc:mysql://localhost/ssop"
    username: "root"
    password: "root" #배포용 비번 Ssop242401@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa :
    hibernate:
      #스프링 시작 시 DB에 있는 테이블을 어떻게 처리할 지
      ddl-auto: validate
      #ddl-auto 속성 종류
        #create : 시작 시 기존 테이블 삭제 후 생성
        #creae-drop : 종료 시 테이블 삭제
        #update : 변경사항만 반영
        #validate : 생성/수정하지 않고 정상 매핑되는지만 검사
        #none : 아무 일도 안일어남
    properties:
      hibernate:
        format_sql: true #JPA 사용해 DB에 SQL날릴 때 SQL을 예쁘게 포맷팅할 지 결정
        show_sql: true #JPA 사용해 DB에 SQL날릴 때 SQL 보여줄 지 결정
        dialect: org.hibernate.dialect.MySQL8Dialect #한국어로 방언, 사투리란 뜻으로 알아서 db끼리 다른 sql 조금씩 수정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client_id: ${kakao.client.id}
            client-secret: ${kakao.client.secret}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost.8080/login/kakao
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  header: Authorization
  secret: c3d1LWRpZ2l0YWxtZWRpYS0yMDI0LXNzb3AtYmFja2VuZC1zcHJpbmctYm9vdC1qd3Qtc2VjcmV0LWtleS10b2tlbi1zc29w
  # swu-digital-media-2024-ssop ~~~ 인코딩한 비밀 키랑 연동 > HS512 알고리즘 사용 > 64byte
  token-validity-in-seconds: 86400    # 초, 24시간